name: Deploy Next.js Customer App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/customer-frontend"

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/customer-frontend

            # Ensure Node.js and PM2 are installed
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm install --lts
            nvm use --lts

            # Install dependencies
            npm ci --omit=dev

            # Setup env
            cp .env.production .env.local

            # Run build
            npm run build

            # Restart via PM2
            pm2 delete customer-app || true
            pm2 start npm --name "customer-app" -- start
            pm2 save
